export const shopAbi = [
  {
    type: "function",
    name: "createOrder",
    inputs: [
      {
        name: "items",
        type: "tuple[]",
        components: [
          { name: "productId", type: "uint256" },
          { name: "variantId", type: "uint256" },
          { name: "quantity", type: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "orderId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "cancelOrder",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fulfillOrder",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "leaveReview",
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "rating", type: "uint8" },
      { name: "_metadataURI", type: "string" },
    ],
    outputs: [{ name: "reviewId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createProduct",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_price", type: "uint256" },
      { name: "_stock", type: "uint256" },
      { name: "_categoryId", type: "uint256" },
      { name: "_metadataURI", type: "string" },
    ],
    outputs: [{ name: "productId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createCategory",
    inputs: [
      { name: "_name", type: "string" },
      { name: "_metadataURI", type: "string" },
    ],
    outputs: [{ name: "categoryId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createDiscount",
    inputs: [
      { name: "code", type: "bytes32" },
      { name: "basisPoints", type: "uint256" },
      { name: "maxUses", type: "uint256" },
      { name: "expiresAt", type: "uint256" },
    ],
    outputs: [{ name: "discountId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "products",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "price", type: "uint256" },
      { name: "stock", type: "uint256" },
      { name: "categoryId", type: "uint256" },
      { name: "metadataURI", type: "string" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "variants",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "uint256" },
    ],
    outputs: [
      { name: "name", type: "string" },
      { name: "price", type: "uint256" },
      { name: "stock", type: "uint256" },
      { name: "active", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "totalAmount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCancelled",
    inputs: [{ name: "orderId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderFulfilled",
    inputs: [{ name: "orderId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "ReviewCreated",
    inputs: [
      { name: "reviewId", type: "uint256", indexed: true },
      { name: "orderId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "rating", type: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProductCreated",
    inputs: [
      { name: "productId", type: "uint256", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "price", type: "uint256", indexed: false },
      { name: "stock", type: "uint256", indexed: false },
      { name: "categoryId", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CategoryCreated",
    inputs: [
      { name: "categoryId", type: "uint256", indexed: true },
      { name: "name", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DiscountCreated",
    inputs: [
      { name: "discountId", type: "uint256", indexed: true },
      { name: "code", type: "bytes32", indexed: false },
      { name: "basisPoints", type: "uint256", indexed: false },
      { name: "maxUses", type: "uint256", indexed: false },
      { name: "expiresAt", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "deliverDigital",
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "payload", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDelivery",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [{ name: "", type: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "leaveFeedback",
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "value", type: "int128" },
      { name: "valueDecimals", type: "uint8" },
      { name: "tag1", type: "string" },
      { name: "feedbackURI", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DigitalDelivery",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "payload", type: "bytes", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeedbackLeft",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "value", type: "int128", indexed: false },
    ],
  },
  // Escrow
  {
    type: "function",
    name: "claimRefund",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEscrowTimeout",
    inputs: [{ name: "_timeout", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrowTimeout",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orders",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "customer", type: "address" },
      { name: "totalAmount", type: "uint256" },
      { name: "protocolFeeAmount", type: "uint256" },
      { name: "escrowAmount", type: "uint256" },
      { name: "status", type: "uint8" },
      { name: "createdAt", type: "uint256" },
      { name: "shippingHash", type: "bytes32" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowTimeoutUpdated",
    inputs: [
      { name: "newTimeout", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
